import asyncio
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent.parent))

from sqlalchemy import select

from app.core.database import async_session_factory as AsyncSessionLocal
from app.models.plant import Plant
from app.services.plant_crawler import normalize_name

PLANTS = [
    # ===== FRUIT TREES =====
    {
        "scientific_name": "olea europaea",
        "scientific_name_full": "Olea europaea L.",
        "common_names_pt": ["Oliveira"],
        "common_names_en": ["Olive"],
        "family": "Oleaceae",
        "genus": "Olea",
        "plant_type": "fruit_tree",
        "kc_initial": 0.65, "kc_mid": 0.70, "kc_late": 0.65,
        "root_depth_cm": 120, "drought_tolerance": "high",
        "row_spacing_cm": 600, "plant_spacing_cm": 600,
        "sun_requirement": "full_sun",
        "soil_ph_min": 5.5, "soil_ph_max": 8.5,
        "soil_texture": ["sandy", "loam"],
        "soil_drainage": "well_drained",
        "usda_zone_min": 8, "usda_zone_max": 11,
        "days_to_maturity_min": 365, "days_to_maturity_max": 730,
        "notes": "Drought-tolerant once established. Requires chill for fruiting.",
        "sources": {"fao_56": {"crop": "olive"}},
    },
    {
        "scientific_name": "citrus sinensis",
        "scientific_name_full": "Citrus sinensis (L.) Osbeck",
        "common_names_pt": ["Laranjeira"],
        "common_names_en": ["Sweet Orange"],
        "family": "Rutaceae",
        "genus": "Citrus",
        "plant_type": "fruit_tree",
        "kc_initial": 0.70, "kc_mid": 0.65, "kc_late": 0.70,
        "root_depth_cm": 90, "drought_tolerance": "medium",
        "row_spacing_cm": 500, "plant_spacing_cm": 500,
        "sun_requirement": "full_sun",
        "soil_ph_min": 5.5, "soil_ph_max": 7.5,
        "soil_texture": ["loam", "sandy"],
        "soil_drainage": "well_drained",
        "usda_zone_min": 9, "usda_zone_max": 11,
        "notes": "Needs regular watering during fruit development.",
        "sources": {"fao_56": {"crop": "citrus"}},
    },
    {
        "scientific_name": "citrus limon",
        "scientific_name_full": "Citrus limon (L.) Osbeck",
        "common_names_pt": ["Limonário", "Limoeiro"],
        "common_names_en": ["Lemon"],
        "family": "Rutaceae",
        "genus": "Citrus",
        "plant_type": "fruit_tree",
        "kc_initial": 0.70, "kc_mid": 0.65, "kc_late": 0.70,
        "root_depth_cm": 90, "drought_tolerance": "medium",
        "row_spacing_cm": 400, "plant_spacing_cm": 400,
        "sun_requirement": "full_sun",
        "soil_ph_min": 5.5, "soil_ph_max": 7.5,
        "soil_texture": ["loam", "sandy"],
        "soil_drainage": "well_drained",
        "usda_zone_min": 9, "usda_zone_max": 11,
        "sources": {"fao_56": {"crop": "citrus"}},
    },
    {
        "scientific_name": "ficus carica",
        "scientific_name_full": "Ficus carica L.",
        "common_names_pt": ["Figueira"],
        "common_names_en": ["Fig"],
        "family": "Moraceae",
        "genus": "Ficus",
        "plant_type": "fruit_tree",
        "kc_initial": 0.50, "kc_mid": 0.75, "kc_late": 0.60,
        "root_depth_cm": 100, "drought_tolerance": "high",
        "row_spacing_cm": 500, "plant_spacing_cm": 500,
        "sun_requirement": "full_sun",
        "soil_ph_min": 6.0, "soil_ph_max": 8.0,
        "soil_texture": ["loam", "sandy", "clay"],
        "soil_drainage": "well_drained",
        "usda_zone_min": 7, "usda_zone_max": 11,
        "notes": "Very drought-tolerant once established.",
        "sources": {"fao_56": {"crop": "fig"}},
    },
    {
        "scientific_name": "prunus dulcis",
        "scientific_name_full": "Prunus dulcis (Mill.) D.A.Webb",
        "common_names_pt": ["Amendoeira"],
        "common_names_en": ["Almond"],
        "family": "Rosaceae",
        "genus": "Prunus",
        "plant_type": "fruit_tree",
        "kc_initial": 0.60, "kc_mid": 0.90, "kc_late": 0.65,
        "root_depth_cm": 120, "drought_tolerance": "medium",
        "row_spacing_cm": 600, "plant_spacing_cm": 600,
        "sun_requirement": "full_sun",
        "soil_ph_min": 6.0, "soil_ph_max": 7.5,
        "soil_texture": ["loam"],
        "soil_drainage": "well_drained",
        "usda_zone_min": 7, "usda_zone_max": 10,
        "chill_hours": 300,
        "sources": {"fao_56": {"crop": "almond"}},
    },
    {
        "scientific_name": "malus domestica",
        "scientific_name_full": "Malus domestica Borkh.",
        "common_names_pt": ["Macieira"],
        "common_names_en": ["Apple"],
        "family": "Rosaceae",
        "genus": "Malus",
        "plant_type": "fruit_tree",
        "kc_initial": 0.45, "kc_mid": 0.95, "kc_late": 0.70,
        "root_depth_cm": 90, "drought_tolerance": "medium",
        "row_spacing_cm": 400, "plant_spacing_cm": 400,
        "sun_requirement": "full_sun",
        "soil_ph_min": 6.0, "soil_ph_max": 7.0,
        "soil_texture": ["loam"],
        "soil_drainage": "well_drained",
        "usda_zone_min": 4, "usda_zone_max": 9,
        "chill_hours": 800,
        "days_to_maturity_min": 120, "days_to_maturity_max": 180,
        "sources": {"fao_56": {"crop": "apple"}},
    },
    {
        "scientific_name": "pyrus communis",
        "scientific_name_full": "Pyrus communis L.",
        "common_names_pt": ["Pereira", "Pereira-comum", "Catapereiro"],
        "common_names_en": ["Pear"],
        "family": "Rosaceae",
        "genus": "Pyrus",
        "plant_type": "fruit_tree",
        "kc_initial": 0.50, "kc_mid": 0.95, "kc_late": 0.70,
        "root_depth_cm": 90, "drought_tolerance": "medium",
        "row_spacing_cm": 400, "plant_spacing_cm": 400,
        "sun_requirement": "full_sun",
        "soil_ph_min": 6.0, "soil_ph_max": 7.5,
        "soil_texture": ["loam"],
        "soil_drainage": "well_drained",
        "usda_zone_min": 5, "usda_zone_max": 9,
        "chill_hours": 600,
        "sources": {"fao_56": {"crop": "pear"}},
    },
    {
        "scientific_name": "prunus persica",
        "scientific_name_full": "Prunus persica (L.) Batsch",
        "common_names_pt": ["Pessegueiro"],
        "common_names_en": ["Peach"],
        "family": "Rosaceae",
        "genus": "Prunus",
        "plant_type": "fruit_tree",
        "kc_initial": 0.45, "kc_mid": 0.90, "kc_late": 0.65,
        "root_depth_cm": 90, "drought_tolerance": "medium",
        "row_spacing_cm": 450, "plant_spacing_cm": 450,
        "sun_requirement": "full_sun",
        "soil_ph_min": 6.0, "soil_ph_max": 7.0,
        "soil_texture": ["loam"],
        "soil_drainage": "well_drained",
        "usda_zone_min": 5, "usda_zone_max": 9,
        "chill_hours": 500,
        "sources": {"fao_56": {"crop": "peach"}},
    },
    {
        "scientific_name": "prunus domestica",
        "scientific_name_full": "Prunus domestica L.",
        "common_names_pt": ["Ameixoeira"],
        "common_names_en": ["Plum"],
        "family": "Rosaceae",
        "genus": "Prunus",
        "plant_type": "fruit_tree",
        "kc_initial": 0.45, "kc_mid": 0.85, "kc_late": 0.65,
        "root_depth_cm": 90, "drought_tolerance": "medium",
        "row_spacing_cm": 400, "plant_spacing_cm": 400,
        "sun_requirement": "full_sun",
        "soil_ph_min": 5.5, "soil_ph_max": 7.5,
        "soil_texture": ["loam"],
        "soil_drainage": "well_drained",
        "usda_zone_min": 5, "usda_zone_max": 9,
        "chill_hours": 700,
        "sources": {"fao_56": {"crop": "plum"}},
    },
    {
        "scientific_name": "punica granatum",
        "scientific_name_full": "Punica granatum L.",
        "common_names_pt": ["Romãzeira"],
        "common_names_en": ["Pomegranate"],
        "family": "Lythraceae",
        "genus": "Punica",
        "plant_type": "fruit_tree",
        "kc_initial": 0.50, "kc_mid": 0.80, "kc_late": 0.60,
        "root_depth_cm": 100, "drought_tolerance": "high",
        "row_spacing_cm": 400, "plant_spacing_cm": 400,
        "sun_requirement": "full_sun",
        "soil_ph_min": 5.5, "soil_ph_max": 7.5,
        "soil_texture": ["loam", "sandy"],
        "soil_drainage": "well_drained",
        "usda_zone_min": 7, "usda_zone_max": 11,
        "sources": {"fao_56": {"crop": "pomegranate"}},
    },
    {
        "scientific_name": "vitis vinifera",
        "scientific_name_full": "Vitis vinifera L.",
        "common_names_pt": ["Videira", "Vinha"],
        "common_names_en": ["Grape vine"],
        "family": "Vitaceae",
        "genus": "Vitis",
        "plant_type": "fruit_tree",
        "kc_initial": 0.30, "kc_mid": 0.70, "kc_late": 0.45,
        "root_depth_cm": 100, "drought_tolerance": "medium",
        "row_spacing_cm": 250, "plant_spacing_cm": 200,
        "sun_requirement": "full_sun",
        "soil_ph_min": 5.5, "soil_ph_max": 7.5,
        "soil_texture": ["loam", "sandy"],
        "soil_drainage": "well_drained",
        "usda_zone_min": 6, "usda_zone_max": 10,
        "notes": "Kc varies by trellis system and row orientation.",
        "sources": {"fao_56": {"crop": "grape"}},
    },
    {
        "scientific_name": "diospyros kaki",
        "scientific_name_full": "Diospyros kaki Thunb.",
        "common_names_pt": ["Diospireiro"],
        "common_names_en": ["Persimmon"],
        "family": "Ebenaceae",
        "genus": "Diospyros",
        "plant_type": "fruit_tree",
        "kc_initial": 0.50, "kc_mid": 0.85, "kc_late": 0.65,
        "root_depth_cm": 90, "drought_tolerance": "medium",
        "row_spacing_cm": 500, "plant_spacing_cm": 500,
        "sun_requirement": "full_sun",
        "soil_ph_min": 6.0, "soil_ph_max": 7.5,
        "soil_texture": ["loam"],
        "soil_drainage": "well_drained",
        "usda_zone_min": 7, "usda_zone_max": 10,
        "sources": {"fao_56": {"crop": "persimmon"}},
    },
    {
        "scientific_name": "morus nigra",
        "scientific_name_full": "Morus nigra L.",
        "common_names_pt": ["Amoreira"],
        "common_names_en": ["Black mulberry"],
        "family": "Moraceae",
        "genus": "Morus",
        "plant_type": "fruit_tree",
        "kc_initial": 0.50, "kc_mid": 0.80, "kc_late": 0.60,
        "root_depth_cm": 100, "drought_tolerance": "high",
        "row_spacing_cm": 600, "plant_spacing_cm": 600,
        "sun_requirement": "full_sun",
        "soil_ph_min": 5.5, "soil_ph_max": 7.5,
        "soil_texture": ["loam", "sandy"],
        "soil_drainage": "well_drained",
        "usda_zone_min": 5, "usda_zone_max": 10,
        "sources": {"fao_56": {"crop": "mulberry"}},
    },
    {
        "scientific_name": "prunus avium",
        "scientific_name_full": "Prunus avium (L.) L.",
        "common_names_pt": ["Cerejeira"],
        "common_names_en": ["Sweet cherry"],
        "family": "Rosaceae",
        "genus": "Prunus",
        "plant_type": "fruit_tree",
        "kc_initial": 0.50, "kc_mid": 0.95, "kc_late": 0.70,
        "root_depth_cm": 90, "drought_tolerance": "low",
        "row_spacing_cm": 500, "plant_spacing_cm": 500,
        "sun_requirement": "full_sun",
        "soil_ph_min": 6.0, "soil_ph_max": 7.5,
        "soil_texture": ["loam"],
        "soil_drainage": "well_drained",
        "usda_zone_min": 5, "usda_zone_max": 9,
        "chill_hours": 700,
        "sources": {"fao_56": {"crop": "cherry"}},
    },
    {
        "scientific_name": "corylus avellana",
        "scientific_name_full": "Corylus avellana L.",
        "common_names_pt": ["Aveleira"],
        "common_names_en": ["Hazelnut"],
        "family": "Betulaceae",
        "genus": "Corylus",
        "plant_type": "fruit_tree",
        "kc_initial": 0.50, "kc_mid": 0.85, "kc_late": 0.65,
        "root_depth_cm": 80, "drought_tolerance": "medium",
        "row_spacing_cm": 400, "plant_spacing_cm": 400,
        "sun_requirement": "part_shade",
        "soil_ph_min": 5.5, "soil_ph_max": 7.0,
        "soil_texture": ["loam"],
        "soil_drainage": "well_drained",
        "usda_zone_min": 4, "usda_zone_max": 9,
        "sources": {"fao_56": {"crop": "hazelnut"}},
    },
    # ===== VEGETABLES =====
    {
        "scientific_name": "solanum lycopersicum",
        "scientific_name_full": "Solanum lycopersicum L.",
        "common_names_pt": ["Tomate"],
        "common_names_en": ["Tomato"],
        "family": "Solanaceae",
        "genus": "Solanum",
        "plant_type": "vegetable",
        "kc_initial": 0.60, "kc_mid": 1.15, "kc_late": 0.80,
        "root_depth_cm": 60, "drought_tolerance": "low",
        "row_spacing_cm": 80, "plant_spacing_cm": 50,
        "sun_requirement": "full_sun",
        "soil_ph_min": 5.8, "soil_ph_max": 7.0,
        "soil_texture": ["loam"],
        "soil_drainage": "well_drained",
        "days_to_maturity_min": 60, "days_to_maturity_max": 90,
        "sowing_method": "transplant",
        "sowing_depth_cm": 0.5,
        "notes": "Consistent watering needed to prevent blossom-end rot.",
        "sources": {"fao_56": {"crop": "tomato"}},
    },
    {
        "scientific_name": "capsicum annuum",
        "scientific_name_full": "Capsicum annuum L.",
        "common_names_pt": ["Pimento"],
        "common_names_en": ["Bell pepper"],
        "family": "Solanaceae",
        "genus": "Capsicum",
        "plant_type": "vegetable",
        "kc_initial": 0.60, "kc_mid": 1.05, "kc_late": 0.90,
        "root_depth_cm": 50, "drought_tolerance": "low",
        "row_spacing_cm": 60, "plant_spacing_cm": 40,
        "sun_requirement": "full_sun",
        "soil_ph_min": 6.0, "soil_ph_max": 7.0,
        "soil_texture": ["loam"],
        "soil_drainage": "well_drained",
        "days_to_maturity_min": 70, "days_to_maturity_max": 90,
        "sowing_method": "transplant",
        "sources": {"fao_56": {"crop": "pepper"}},
    },
    {
        "scientific_name": "cucumis sativus",
        "scientific_name_full": "Cucumis sativus L.",
        "common_names_pt": ["Pepino"],
        "common_names_en": ["Cucumber"],
        "family": "Cucurbitaceae",
        "genus": "Cucumis",
        "plant_type": "vegetable",
        "kc_initial": 0.60, "kc_mid": 1.00, "kc_late": 0.75,
        "root_depth_cm": 50, "drought_tolerance": "low",
        "row_spacing_cm": 90, "plant_spacing_cm": 30,
        "sun_requirement": "full_sun",
        "soil_ph_min": 6.0, "soil_ph_max": 7.0,
        "soil_texture": ["loam", "sandy"],
        "soil_drainage": "well_drained",
        "days_to_maturity_min": 55, "days_to_maturity_max": 70,
        "sowing_method": "direct",
        "sowing_depth_cm": 1.5,
        "sources": {"fao_56": {"crop": "cucumber"}},
    },
    {
        "scientific_name": "cucurbita pepo",
        "scientific_name_full": "Cucurbita pepo L.",
        "common_names_pt": ["Courgette", "Abobrinha"],
        "common_names_en": ["Zucchini"],
        "family": "Cucurbitaceae",
        "genus": "Cucurbita",
        "plant_type": "vegetable",
        "kc_initial": 0.50, "kc_mid": 0.95, "kc_late": 0.75,
        "root_depth_cm": 60, "drought_tolerance": "medium",
        "row_spacing_cm": 90, "plant_spacing_cm": 60,
        "sun_requirement": "full_sun",
        "soil_ph_min": 6.0, "soil_ph_max": 7.5,
        "soil_texture": ["loam"],
        "soil_drainage": "well_drained",
        "days_to_maturity_min": 50, "days_to_maturity_max": 70,
        "sowing_method": "direct",
        "sowing_depth_cm": 2.0,
        "sources": {"fao_56": {"crop": "squash"}},
    },
    {
        "scientific_name": "lactuca sativa",
        "scientific_name_full": "Lactuca sativa L.",
        "common_names_pt": ["Alface"],
        "common_names_en": ["Lettuce"],
        "family": "Asteraceae",
        "genus": "Lactuca",
        "plant_type": "vegetable",
        "kc_initial": 0.50, "kc_mid": 0.95, "kc_late": 0.90,
        "root_depth_cm": 30, "drought_tolerance": "low",
        "row_spacing_cm": 30, "plant_spacing_cm": 25,
        "sun_requirement": "part_shade",
        "soil_ph_min": 6.0, "soil_ph_max": 7.0,
        "soil_texture": ["loam", "sandy"],
        "soil_drainage": "well_drained",
        "days_to_maturity_min": 30, "days_to_maturity_max": 70,
        "sowing_method": "direct",
        "sowing_depth_cm": 0.5,
        "notes": "Shallow roots — needs frequent light watering.",
        "sources": {"fao_56": {"crop": "lettuce"}},
    },
    {
        "scientific_name": "spinacia oleracea",
        "scientific_name_full": "Spinacia oleracea L.",
        "common_names_pt": ["Espinafre"],
        "common_names_en": ["Spinach"],
        "family": "Amaranthaceae",
        "genus": "Spinacia",
        "plant_type": "vegetable",
        "kc_initial": 0.50, "kc_mid": 0.95, "kc_late": 0.90,
        "root_depth_cm": 30, "drought_tolerance": "low",
        "row_spacing_cm": 30, "plant_spacing_cm": 15,
        "sun_requirement": "part_shade",
        "soil_ph_min": 6.0, "soil_ph_max": 7.5,
        "soil_texture": ["loam"],
        "soil_drainage": "well_drained",
        "days_to_maturity_min": 40, "days_to_maturity_max": 50,
        "sowing_method": "direct",
        "sowing_depth_cm": 1.0,
        "sources": {"fao_56": {"crop": "spinach"}},
    },
    {
        "scientific_name": "brassica oleracea var. capitata",
        "scientific_name_full": "Brassica oleracea var. capitata L.",
        "common_names_pt": ["Couve-repolho"],
        "common_names_en": ["Cabbage"],
        "family": "Brassicaceae",
        "genus": "Brassica",
        "plant_type": "vegetable",
        "kc_initial": 0.45, "kc_mid": 1.00, "kc_late": 0.80,
        "root_depth_cm": 60, "drought_tolerance": "medium",
        "row_spacing_cm": 60, "plant_spacing_cm": 40,
        "sun_requirement": "full_sun",
        "soil_ph_min": 6.0, "soil_ph_max": 7.5,
        "soil_texture": ["loam"],
        "soil_drainage": "well_drained",
        "days_to_maturity_min": 70, "days_to_maturity_max": 120,
        "sowing_method": "transplant",
        "sowing_depth_cm": 0.5,
        "sources": {"fao_56": {"crop": "cabbage"}},
    },
    {
        "scientific_name": "daucus carota",
        "scientific_name_full": "Daucus carota subsp. sativus (Hoffm.) Schübl. & G.Martens",
        "common_names_pt": ["Cenoura"],
        "common_names_en": ["Carrot"],
        "family": "Apiaceae",
        "genus": "Daucus",
        "plant_type": "vegetable",
        "kc_initial": 0.50, "kc_mid": 1.00, "kc_late": 0.80,
        "root_depth_cm": 60, "drought_tolerance": "medium",
        "row_spacing_cm": 30, "plant_spacing_cm": 5,
        "sun_requirement": "full_sun",
        "soil_ph_min": 6.0, "soil_ph_max": 7.0,
        "soil_texture": ["sandy"],
        "soil_drainage": "well_drained",
        "days_to_maturity_min": 60, "days_to_maturity_max": 80,
        "sowing_method": "direct",
        "sowing_depth_cm": 0.5,
        "notes": "Loose, sandy soil for good root development.",
        "sources": {"fao_56": {"crop": "carrot"}},
    },
    {
        "scientific_name": "allium cepa",
        "scientific_name_full": "Allium cepa L.",
        "common_names_pt": ["Cebola"],
        "common_names_en": ["Onion"],
        "family": "Amaryllidaceae",
        "genus": "Allium",
        "plant_type": "vegetable",
        "kc_initial": 0.50, "kc_mid": 1.00, "kc_late": 0.75,
        "root_depth_cm": 30, "drought_tolerance": "medium",
        "row_spacing_cm": 30, "plant_spacing_cm": 10,
        "sun_requirement": "full_sun",
        "soil_ph_min": 6.0, "soil_ph_max": 7.0,
        "soil_texture": ["loam", "sandy"],
        "soil_drainage": "well_drained",
        "days_to_maturity_min": 100, "days_to_maturity_max": 150,
        "sowing_method": "direct",
        "sowing_depth_cm": 1.0,
        "sources": {"fao_56": {"crop": "onion"}},
    },
    {
        "scientific_name": "allium sativum",
        "scientific_name_full": "Allium sativum L.",
        "common_names_pt": ["Alho"],
        "common_names_en": ["Garlic"],
        "family": "Amaryllidaceae",
        "genus": "Allium",
        "plant_type": "vegetable",
        "kc_initial": 0.50, "kc_mid": 1.00, "kc_late": 0.75,
        "root_depth_cm": 30, "drought_tolerance": "medium",
        "row_spacing_cm": 30, "plant_spacing_cm": 10,
        "sun_requirement": "full_sun",
        "soil_ph_min": 6.0, "soil_ph_max": 7.5,
        "soil_texture": ["loam", "sandy"],
        "soil_drainage": "well_drained",
        "days_to_maturity_min": 90, "days_to_maturity_max": 180,
        "sowing_method": "direct",
        "sowing_depth_cm": 3.0,
        "notes": "Plant cloves in autumn for summer harvest.",
        "sources": {"fao_56": {"crop": "garlic"}},
    },
    {
        "scientific_name": "solanum tuberosum",
        "scientific_name_full": "Solanum tuberosum L.",
        "common_names_pt": ["Batata"],
        "common_names_en": ["Potato"],
        "family": "Solanaceae",
        "genus": "Solanum",
        "plant_type": "vegetable",
        "kc_initial": 0.50, "kc_mid": 1.10, "kc_late": 0.75,
        "root_depth_cm": 50, "drought_tolerance": "medium",
        "row_spacing_cm": 70, "plant_spacing_cm": 30,
        "sun_requirement": "full_sun",
        "soil_ph_min": 5.0, "soil_ph_max": 6.5,
        "soil_texture": ["loam", "sandy"],
        "soil_drainage": "well_drained",
        "days_to_maturity_min": 90, "days_to_maturity_max": 120,
        "sowing_method": "direct",
        "sowing_depth_cm": 10.0,
        "notes": "Hilling up improves yield.",
        "sources": {"fao_56": {"crop": "potato"}},
    },
    {
        "scientific_name": "ipomoea batatas",
        "scientific_name_full": "Ipomoea batatas (L.) Lam.",
        "common_names_pt": ["Batata-doce"],
        "common_names_en": ["Sweet potato"],
        "family": "Convolvulaceae",
        "genus": "Ipomoea",
        "plant_type": "vegetable",
        "kc_initial": 0.50, "kc_mid": 1.10, "kc_late": 0.65,
        "root_depth_cm": 60, "drought_tolerance": "medium",
        "row_spacing_cm": 90, "plant_spacing_cm": 30,
        "sun_requirement": "full_sun",
        "soil_ph_min": 5.5, "soil_ph_max": 6.5,
        "soil_texture": ["sandy"],
        "soil_drainage": "well_drained",
        "days_to_maturity_min": 100, "days_to_maturity_max": 140,
        "sowing_method": "transplant",
        "sources": {"fao_56": {"crop": "sweet potato"}},
    },
    {
        "scientific_name": "phaseolus vulgaris",
        "scientific_name_full": "Phaseolus vulgaris L.",
        "common_names_pt": ["Feijão"],
        "common_names_en": ["Bean"],
        "family": "Fabaceae",
        "genus": "Phaseolus",
        "plant_type": "vegetable",
        "kc_initial": 0.50, "kc_mid": 1.05, "kc_late": 0.65,
        "root_depth_cm": 50, "drought_tolerance": "medium",
        "row_spacing_cm": 50, "plant_spacing_cm": 10,
        "sun_requirement": "full_sun",
        "soil_ph_min": 6.0, "soil_ph_max": 7.0,
        "soil_texture": ["loam"],
        "soil_drainage": "well_drained",
        "days_to_maturity_min": 55, "days_to_maturity_max": 70,
        "sowing_method": "direct",
        "sowing_depth_cm": 3.0,
        "notes": "Nitrogen-fixing — good rotation crop.",
        "sources": {"fao_56": {"crop": "bean"}},
    },
    {
        "scientific_name": "pisum sativum",
        "scientific_name_full": "Pisum sativum L.",
        "common_names_pt": ["Ervilha"],
        "common_names_en": ["Pea"],
        "family": "Fabaceae",
        "genus": "Pisum",
        "plant_type": "vegetable",
        "kc_initial": 0.50, "kc_mid": 1.05, "kc_late": 0.95,
        "root_depth_cm": 50, "drought_tolerance": "medium",
        "row_spacing_cm": 60, "plant_spacing_cm": 5,
        "sun_requirement": "full_sun",
        "soil_ph_min": 6.0, "soil_ph_max": 7.5,
        "soil_texture": ["loam"],
        "soil_drainage": "well_drained",
        "days_to_maturity_min": 55, "days_to_maturity_max": 80,
        "sowing_method": "direct",
        "sowing_depth_cm": 3.0,
        "notes": "Cool-season crop.",
        "sources": {"fao_56": {"crop": "pea"}},
    },
    {
        "scientific_name": "cucumis melo",
        "scientific_name_full": "Cucumis melo L.",
        "common_names_pt": ["Melão"],
        "common_names_en": ["Melon"],
        "family": "Cucurbitaceae",
        "genus": "Cucumis",
        "plant_type": "vegetable",
        "kc_initial": 0.50, "kc_mid": 1.05, "kc_late": 0.75,
        "root_depth_cm": 60, "drought_tolerance": "medium",
        "row_spacing_cm": 100, "plant_spacing_cm": 50,
        "sun_requirement": "full_sun",
        "soil_ph_min": 6.0, "soil_ph_max": 7.0,
        "soil_texture": ["loam", "sandy"],
        "soil_drainage": "well_drained",
        "days_to_maturity_min": 70, "days_to_maturity_max": 100,
        "sowing_method": "direct",
        "sowing_depth_cm": 1.5,
        "sources": {"fao_56": {"crop": "melon"}},
    },
    {
        "scientific_name": "citrullus lanatus",
        "scientific_name_full": "Citrullus lanatus (Thunb.) Matsum. & Nakai",
        "common_names_pt": ["Melancia"],
        "common_names_en": ["Watermelon"],
        "family": "Cucurbitaceae",
        "genus": "Citrullus",
        "plant_type": "vegetable",
        "kc_initial": 0.50, "kc_mid": 1.05, "kc_late": 0.75,
        "root_depth_cm": 80, "drought_tolerance": "medium",
        "row_spacing_cm": 150, "plant_spacing_cm": 60,
        "sun_requirement": "full_sun",
        "soil_ph_min": 6.0, "soil_ph_max": 7.5,
        "soil_texture": ["sandy"],
        "soil_drainage": "well_drained",
        "days_to_maturity_min": 80, "days_to_maturity_max": 100,
        "sowing_method": "direct",
        "sowing_depth_cm": 2.0,
        "notes": "Needs warm soil to germinate.",
        "sources": {"fao_56": {"crop": "watermelon"}},
    },
    {
        "scientific_name": "fragaria × ananassa",
        "scientific_name_full": "Fragaria × ananassa Duchesne",
        "common_names_pt": ["Morango"],
        "common_names_en": ["Strawberry"],
        "family": "Rosaceae",
        "genus": "Fragaria",
        "plant_type": "vegetable",
        "kc_initial": 0.40, "kc_mid": 0.85, "kc_late": 0.75,
        "root_depth_cm": 20, "drought_tolerance": "low",
        "row_spacing_cm": 40, "plant_spacing_cm": 30,
        "sun_requirement": "full_sun",
        "soil_ph_min": 5.5, "soil_ph_max": 6.5,
        "soil_texture": ["loam", "sandy"],
        "soil_drainage": "well_drained",
        "days_to_maturity_min": 60, "days_to_maturity_max": 90,
        "sowing_method": "transplant",
        "notes": "Shallow roots — needs consistent moisture.",
        "sources": {"fao_56": {"crop": "strawberry"}},
    },
    {
        "scientific_name": "solanum melongena",
        "scientific_name_full": "Solanum melongena L.",
        "common_names_pt": ["Beringela"],
        "common_names_en": ["Eggplant"],
        "family": "Solanaceae",
        "genus": "Solanum",
        "plant_type": "vegetable",
        "kc_initial": 0.60, "kc_mid": 1.05, "kc_late": 0.85,
        "root_depth_cm": 60, "drought_tolerance": "medium",
        "row_spacing_cm": 70, "plant_spacing_cm": 50,
        "sun_requirement": "full_sun",
        "soil_ph_min": 5.8, "soil_ph_max": 7.0,
        "soil_texture": ["loam"],
        "soil_drainage": "well_drained",
        "days_to_maturity_min": 70, "days_to_maturity_max": 90,
        "sowing_method": "transplant",
        "sources": {"fao_56": {"crop": "eggplant"}},
    },
    {
        "scientific_name": "brassica oleracea var. italica",
        "scientific_name_full": "Brassica oleracea var. italica Plenck",
        "common_names_pt": ["Brócolos"],
        "common_names_en": ["Broccoli"],
        "family": "Brassicaceae",
        "genus": "Brassica",
        "plant_type": "vegetable",
        "kc_initial": 0.45, "kc_mid": 1.00, "kc_late": 0.80,
        "root_depth_cm": 60, "drought_tolerance": "medium",
        "row_spacing_cm": 50, "plant_spacing_cm": 40,
        "sun_requirement": "full_sun",
        "soil_ph_min": 6.0, "soil_ph_max": 7.0,
        "soil_texture": ["loam"],
        "soil_drainage": "well_drained",
        "days_to_maturity_min": 60, "days_to_maturity_max": 100,
        "sowing_method": "transplant",
        "sowing_depth_cm": 0.5,
        "sources": {"fao_56": {"crop": "broccoli"}},
    },
    {
        "scientific_name": "brassica oleracea var. botrytis",
        "scientific_name_full": "Brassica oleracea var. botrytis L.",
        "common_names_pt": ["Couve-flor"],
        "common_names_en": ["Cauliflower"],
        "family": "Brassicaceae",
        "genus": "Brassica",
        "plant_type": "vegetable",
        "kc_initial": 0.45, "kc_mid": 1.00, "kc_late": 0.80,
        "root_depth_cm": 60, "drought_tolerance": "low",
        "row_spacing_cm": 60, "plant_spacing_cm": 40,
        "sun_requirement": "full_sun",
        "soil_ph_min": 6.0, "soil_ph_max": 7.0,
        "soil_texture": ["loam"],
        "soil_drainage": "well_drained",
        "days_to_maturity_min": 70, "days_to_maturity_max": 120,
        "sowing_method": "transplant",
        "sowing_depth_cm": 0.5,
        "notes": "Needs consistent moisture for head formation.",
        "sources": {"fao_56": {"crop": "cauliflower"}},
    },
    {
        "scientific_name": "cucurbita maxima",
        "scientific_name_full": "Cucurbita maxima Duchesne",
        "common_names_pt": ["Abóbora"],
        "common_names_en": ["Pumpkin"],
        "family": "Cucurbitaceae",
        "genus": "Cucurbita",
        "plant_type": "vegetable",
        "kc_initial": 0.50, "kc_mid": 0.95, "kc_late": 0.75,
        "root_depth_cm": 80, "drought_tolerance": "medium",
        "row_spacing_cm": 150, "plant_spacing_cm": 80,
        "sun_requirement": "full_sun",
        "soil_ph_min": 6.0, "soil_ph_max": 7.5,
        "soil_texture": ["loam"],
        "soil_drainage": "well_drained",
        "days_to_maturity_min": 100, "days_to_maturity_max": 140,
        "sowing_method": "direct",
        "sowing_depth_cm": 2.5,
        "sources": {"fao_56": {"crop": "pumpkin"}},
    },
    {
        "scientific_name": "beta vulgaris",
        "scientific_name_full": "Beta vulgaris L.",
        "common_names_pt": ["Beterraba"],
        "common_names_en": ["Beetroot"],
        "family": "Amaranthaceae",
        "genus": "Beta",
        "plant_type": "vegetable",
        "kc_initial": 0.50, "kc_mid": 1.00, "kc_late": 0.80,
        "root_depth_cm": 60, "drought_tolerance": "medium",
        "row_spacing_cm": 30, "plant_spacing_cm": 8,
        "sun_requirement": "full_sun",
        "soil_ph_min": 6.0, "soil_ph_max": 7.5,
        "soil_texture": ["loam", "sandy"],
        "soil_drainage": "well_drained",
        "days_to_maturity_min": 55, "days_to_maturity_max": 80,
        "sowing_method": "direct",
        "sowing_depth_cm": 1.5,
        "sources": {"fao_56": {"crop": "beetroot"}},
    },
    {
        "scientific_name": "zea mays",
        "scientific_name_full": "Zea mays L.",
        "common_names_pt": ["Milho"],
        "common_names_en": ["Corn", "Maize"],
        "family": "Poaceae",
        "genus": "Zea",
        "plant_type": "vegetable",
        "kc_initial": 0.30, "kc_mid": 1.15, "kc_late": 0.60,
        "root_depth_cm": 80, "drought_tolerance": "low",
        "row_spacing_cm": 75, "plant_spacing_cm": 20,
        "sun_requirement": "full_sun",
        "soil_ph_min": 5.8, "soil_ph_max": 7.0,
        "soil_texture": ["loam"],
        "soil_drainage": "well_drained",
        "days_to_maturity_min": 70, "days_to_maturity_max": 100,
        "sowing_method": "direct",
        "sowing_depth_cm": 3.0,
        "sources": {"fao_56": {"crop": "maize"}},
    },
    # ===== HERBS =====
    {
        "scientific_name": "ocimum basilicum",
        "scientific_name_full": "Ocimum basilicum L.",
        "common_names_pt": ["Manjericão"],
        "common_names_en": ["Basil"],
        "family": "Lamiaceae",
        "genus": "Ocimum",
        "plant_type": "herb",
        "kc_initial": 0.60, "kc_mid": 1.05, "kc_late": 0.85,
        "root_depth_cm": 30, "drought_tolerance": "low",
        "row_spacing_cm": 30, "plant_spacing_cm": 25,
        "sun_requirement": "full_sun",
        "soil_ph_min": 5.5, "soil_ph_max": 7.0,
        "soil_texture": ["loam"],
        "soil_drainage": "well_drained",
        "days_to_maturity_min": 60, "days_to_maturity_max": 90,
        "sowing_method": "transplant",
        "sowing_depth_cm": 0.5,
        "notes": "Needs warm soil. Pinch tops for bushier growth.",
        "sources": {"fao_56": {"crop": "basil"}},
    },
    {
        "scientific_name": "rosmarinus officinalis",
        "scientific_name_full": "Rosmarinus officinalis L.",
        "common_names_pt": ["Alecrim"],
        "common_names_en": ["Rosemary"],
        "family": "Lamiaceae",
        "genus": "Salvia",
        "plant_type": "herb",
        "kc_initial": 0.30, "kc_mid": 0.50, "kc_late": 0.40,
        "root_depth_cm": 60, "drought_tolerance": "high",
        "row_spacing_cm": 60, "plant_spacing_cm": 50,
        "sun_requirement": "full_sun",
        "soil_ph_min": 6.0, "soil_ph_max": 8.0,
        "soil_texture": ["sandy", "loam"],
        "soil_drainage": "well_drained",
        "usda_zone_min": 7, "usda_zone_max": 11,
        "days_to_maturity_min": 90, "days_to_maturity_max": 120,
        "sowing_method": "transplant",
        "sources": {"fao_56": {"crop": "rosemary"}},
    },
    {
        "scientific_name": "thymus vulgaris",
        "scientific_name_full": "Thymus vulgaris L.",
        "common_names_pt": ["Tomilho"],
        "common_names_en": ["Thyme"],
        "family": "Lamiaceae",
        "genus": "Thymus",
        "plant_type": "herb",
        "kc_initial": 0.30, "kc_mid": 0.50, "kc_late": 0.40,
        "root_depth_cm": 30, "drought_tolerance": "high",
        "row_spacing_cm": 30, "plant_spacing_cm": 30,
        "sun_requirement": "full_sun",
        "soil_ph_min": 6.5, "soil_ph_max": 8.0,
        "soil_texture": ["sandy"],
        "soil_drainage": "well_drained",
        "usda_zone_min": 5, "usda_zone_max": 9,
        "sowing_method": "transplant",
        "sources": {"fao_56": {"crop": "thyme"}},
    },
    {
        "scientific_name": "origanum vulgare",
        "scientific_name_full": "Origanum vulgare L.",
        "common_names_pt": ["Orégão"],
        "common_names_en": ["Oregano"],
        "family": "Lamiaceae",
        "genus": "Origanum",
        "plant_type": "herb",
        "kc_initial": 0.30, "kc_mid": 0.55, "kc_late": 0.45,
        "root_depth_cm": 40, "drought_tolerance": "high",
        "row_spacing_cm": 30, "plant_spacing_cm": 30,
        "sun_requirement": "full_sun",
        "soil_ph_min": 6.0, "soil_ph_max": 8.0,
        "soil_texture": ["sandy", "loam"],
        "soil_drainage": "well_drained",
        "usda_zone_min": 5, "usda_zone_max": 10,
        "sowing_method": "transplant",
        "sources": {"fao_56": {"crop": "oregano"}},
    },
    {
        "scientific_name": "mentha spicata",
        "scientific_name_full": "Mentha spicata L.",
        "common_names_pt": ["Hortelã"],
        "common_names_en": ["Mint"],
        "family": "Lamiaceae",
        "genus": "Mentha",
        "plant_type": "herb",
        "kc_initial": 0.60, "kc_mid": 1.00, "kc_late": 0.80,
        "root_depth_cm": 30, "drought_tolerance": "low",
        "row_spacing_cm": 40, "plant_spacing_cm": 40,
        "sun_requirement": "part_shade",
        "soil_ph_min": 6.0, "soil_ph_max": 7.5,
        "soil_texture": ["loam"],
        "soil_drainage": "moist",
        "days_to_maturity_min": 60, "days_to_maturity_max": 90,
        "sowing_method": "transplant",
        "notes": "Invasive — grow in containers.",
        "sources": {"fao_56": {"crop": "mint"}},
    },
    {
        "scientific_name": "petroselinum crispum",
        "scientific_name_full": "Petroselinum crispum (Mill.) Fuss",
        "common_names_pt": ["Salsa"],
        "common_names_en": ["Parsley"],
        "family": "Apiaceae",
        "genus": "Petroselinum",
        "plant_type": "herb",
        "kc_initial": 0.55, "kc_mid": 0.95, "kc_late": 0.85,
        "root_depth_cm": 30, "drought_tolerance": "medium",
        "row_spacing_cm": 25, "plant_spacing_cm": 20,
        "sun_requirement": "part_shade",
        "soil_ph_min": 6.0, "soil_ph_max": 7.0,
        "soil_texture": ["loam"],
        "soil_drainage": "well_drained",
        "days_to_maturity_min": 70, "days_to_maturity_max": 90,
        "sowing_method": "direct",
        "sowing_depth_cm": 0.5,
        "notes": "Soak seeds before planting for better germination.",
        "sources": {"fao_56": {"crop": "parsley"}},
    },
    {
        "scientific_name": "coriandrum sativum",
        "scientific_name_full": "Coriandrum sativum L.",
        "common_names_pt": ["Coentros"],
        "common_names_en": ["Coriander", "Cilantro"],
        "family": "Apiaceae",
        "genus": "Coriandrum",
        "plant_type": "herb",
        "kc_initial": 0.55, "kc_mid": 0.95, "kc_late": 0.85,
        "root_depth_cm": 30, "drought_tolerance": "medium",
        "row_spacing_cm": 20, "plant_spacing_cm": 15,
        "sun_requirement": "part_shade",
        "soil_ph_min": 6.0, "soil_ph_max": 7.5,
        "soil_texture": ["loam"],
        "soil_drainage": "well_drained",
        "days_to_maturity_min": 40, "days_to_maturity_max": 60,
        "sowing_method": "direct",
        "sowing_depth_cm": 0.5,
        "notes": "Bolts quickly in heat.",
        "sources": {"fao_56": {"crop": "coriander"}},
    },
    {
        "scientific_name": "salvia officinalis",
        "scientific_name_full": "Salvia officinalis L.",
        "common_names_pt": ["Sálvia"],
        "common_names_en": ["Sage"],
        "family": "Lamiaceae",
        "genus": "Salvia",
        "plant_type": "herb",
        "kc_initial": 0.30, "kc_mid": 0.55, "kc_late": 0.45,
        "root_depth_cm": 50, "drought_tolerance": "high",
        "row_spacing_cm": 50, "plant_spacing_cm": 40,
        "sun_requirement": "full_sun",
        "soil_ph_min": 6.0, "soil_ph_max": 7.5,
        "soil_texture": ["sandy", "loam"],
        "soil_drainage": "well_drained",
        "usda_zone_min": 5, "usda_zone_max": 9,
        "sowing_method": "transplant",
        "sources": {"fao_56": {"crop": "sage"}},
    },
    {
        "scientific_name": "lavandula angustifolia",
        "scientific_name_full": "Lavandula angustifolia Mill.",
        "common_names_pt": ["Lavanda", "Alfazema"],
        "common_names_en": ["Lavender"],
        "family": "Lamiaceae",
        "genus": "Lavandula",
        "plant_type": "herb",
        "kc_initial": 0.25, "kc_mid": 0.45, "kc_late": 0.35,
        "root_depth_cm": 60, "drought_tolerance": "high",
        "row_spacing_cm": 60, "plant_spacing_cm": 50,
        "sun_requirement": "full_sun",
        "soil_ph_min": 6.5, "soil_ph_max": 8.0,
        "soil_texture": ["sandy", "loam"],
        "soil_drainage": "well_drained",
        "usda_zone_min": 5, "usda_zone_max": 9,
        "sowing_method": "transplant",
        "notes": "Prune after flowering to maintain shape.",
        "sources": {"fao_56": {"crop": "lavender"}},
    },
    # ===== FLOWERS =====
    {
        "scientific_name": "helianthus annuus",
        "scientific_name_full": "Helianthus annuus L.",
        "common_names_pt": ["Girassol"],
        "common_names_en": ["Sunflower"],
        "family": "Asteraceae",
        "genus": "Helianthus",
        "plant_type": "flower",
        "kc_initial": 0.35, "kc_mid": 0.85, "kc_late": 0.50,
        "root_depth_cm": 100, "drought_tolerance": "high",
        "row_spacing_cm": 60, "plant_spacing_cm": 30,
        "sun_requirement": "full_sun",
        "soil_ph_min": 6.0, "soil_ph_max": 7.5,
        "soil_texture": ["loam"],
        "soil_drainage": "well_drained",
        "days_to_maturity_min": 55, "days_to_maturity_max": 70,
        "sowing_method": "direct",
        "sowing_depth_cm": 2.0,
        "sources": {"fao_56": {"crop": "sunflower"}},
    },
    {
        "scientific_name": "tagetes erecta",
        "scientific_name_full": "Tagetes erecta L.",
        "common_names_pt": ["Cravo-de-defunto"],
        "common_names_en": ["Marigold"],
        "family": "Asteraceae",
        "genus": "Tagetes",
        "plant_type": "flower",
        "kc_initial": 0.50, "kc_mid": 0.85, "kc_late": 0.70,
        "root_depth_cm": 30, "drought_tolerance": "medium",
        "row_spacing_cm": 30, "plant_spacing_cm": 25,
        "sun_requirement": "full_sun",
        "soil_ph_min": 6.0, "soil_ph_max": 7.5,
        "soil_texture": ["loam"],
        "soil_drainage": "well_drained",
        "days_to_maturity_min": 60, "days_to_maturity_max": 80,
        "sowing_method": "direct",
        "sowing_depth_cm": 0.5,
        "notes": "Good companion plant — deters nematodes.",
        "sources": {"fao_56": {"crop": "marigold"}},
    },
    {
        "scientific_name": "tropaeolum majus",
        "scientific_name_full": "Tropaeolum majus L.",
        "common_names_pt": ["Capuchinha"],
        "common_names_en": ["Nasturtium"],
        "family": "Tropaeolaceae",
        "genus": "Tropaeolum",
        "plant_type": "flower",
        "kc_initial": 0.45, "kc_mid": 0.80, "kc_late": 0.65,
        "root_depth_cm": 20, "drought_tolerance": "medium",
        "row_spacing_cm": 30, "plant_spacing_cm": 25,
        "sun_requirement": "full_sun",
        "soil_ph_min": 6.0, "soil_ph_max": 7.5,
        "soil_texture": ["loam", "sandy"],
        "soil_drainage": "well_drained",
        "days_to_maturity_min": 55, "days_to_maturity_max": 70,
        "sowing_method": "direct",
        "sowing_depth_cm": 1.0,
        "notes": "Edible flowers and leaves. Good trap crop for aphids.",
        "sources": {"fao_56": {"crop": "nasturtium"}},
    },
    {
        "scientific_name": "viola tricolor",
        "scientific_name_full": "Viola tricolor L.",
        "common_names_pt": ["Amor-perfeito"],
        "common_names_en": ["Pansy"],
        "family": "Violaceae",
        "genus": "Viola",
        "plant_type": "flower",
        "kc_initial": 0.45, "kc_mid": 0.80, "kc_late": 0.65,
        "root_depth_cm": 15, "drought_tolerance": "low",
        "row_spacing_cm": 20, "plant_spacing_cm": 15,
        "sun_requirement": "part_shade",
        "soil_ph_min": 5.5, "soil_ph_max": 7.0,
        "soil_texture": ["loam"],
        "soil_drainage": "well_drained",
        "days_to_maturity_min": 60, "days_to_maturity_max": 90,
        "sowing_method": "transplant",
        "sources": {"fao_56": {"crop": "pansy"}},
    },
    {
        "scientific_name": "calendula officinalis",
        "scientific_name_full": "Calendula officinalis L.",
        "common_names_pt": ["Calêndula"],
        "common_names_en": ["Pot marigold"],
        "family": "Asteraceae",
        "genus": "Calendula",
        "plant_type": "flower",
        "kc_initial": 0.45, "kc_mid": 0.80, "kc_late": 0.65,
        "root_depth_cm": 30, "drought_tolerance": "medium",
        "row_spacing_cm": 30, "plant_spacing_cm": 25,
        "sun_requirement": "full_sun",
        "soil_ph_min": 6.0, "soil_ph_max": 7.5,
        "soil_texture": ["loam"],
        "soil_drainage": "well_drained",
        "days_to_maturity_min": 55, "days_to_maturity_max": 65,
        "sowing_method": "direct",
        "sowing_depth_cm": 0.5,
        "notes": "Edible flowers. Good companion for vegetables.",
        "sources": {"fao_56": {"crop": "calendula"}},
    },
]


async def main():
    from app.core.database import engine
    from app.models.base import Base
    async with engine.begin() as conn:
        await conn.run_sync(Base.metadata.create_all)

    async with AsyncSessionLocal() as db:
        for data in PLANTS:
            normalized = normalize_name(data["scientific_name"])
            existing = await db.execute(
                select(Plant).where(Plant.scientific_name == normalized)
            )
            if existing.scalar_one_or_none():
                print(f"SKIP {normalized} — already exists")
                continue
            plant = Plant(**data)
            plant.scientific_name = normalized
            db.add(plant)
            print(f"ADD {normalized}")
        await db.commit()
    print("Done.")


if __name__ == "__main__":
    asyncio.run(main())
